### ISSUE TITLE
Issue with responsiveness in CSS

### ISSUE THREAD

**Issue by 404mahdi** [404mahdi/responsive-navbar-design-using-html-css#1]
Hero section starts from the very the left edge after screen size > 992 px until the screen size is extended to a suitable amount of width as the padding added inside the media query.
If I add padding outside media the alignment gets broken.
margin is 0 auto for the hero section. 
Here's an image of the issue.
![image](https://github.com/404mahdi/responsive-navbar-design-using-html-css/assets/119351159/74f38475-14b8-45c7-ad2b-d26ce1c68969)

**Comment by c-v-pop** [comment]
@media (max-width: 1230px) {

    .hero {
        padding: 0 2em;
    }

}
This solution worked for me, are you happy with it ?
